# Generated by Django 3.1.6 on 2021-02-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='flag',
            field=models.CharField(choices=[('Wait', 'Waiting for machine'), ('Run', 'Running'), ('Finished', 'Finished'), ('Stopping', 'Pending Stop'), ('Stoped', 'Stoped'), ('Error', 'Error')], default=('Wait', 'Waiting for machine'), editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='result',
            field=models.OneToOneField(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Session.result'),
        ),
    ]
