# Generated by Django 3.1.6 on 2021-02-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_auto_20210210_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='flag',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Running', 'Running'), ('Finished', 'Finished'), ('Stopping', 'Stopping'), ('Stoped', 'Stoped'), ('Error', 'Error')], default=('Waiting', 'Waiting'), editable=False, max_length=25),
        ),
    ]
