# Generated by Django 3.1.6 on 2021-02-10 21:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'CPU'), (2, 'GPU')], max_length=3)),
                ('password', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
