# Generated by Django 3.1.6 on 2021-02-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_auto_20210210_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU')], max_length=20),
        ),
    ]
